### ISSUE TITLE
KG-36: Поднять локально Postgres у всех

### ISSUE THREAD

**Issue by evgenymarkov** [urfu-2017/team4#83]

**Comment by evgenymarkov** [comment]
На сервере нужно создать директорию postgres, а в ней docker-compose.yml:
```
version: '3.1'

services:
  postgres:
    image: postgres:10-alpine
    container_name: team4-postgres
    hostname: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 7432:5432
    environment:
      - POSTGRES_DB=kilogram
      - POSTGRES_USER=kilogram
      - POSTGRES_PASSWORD=kilogram4
```
